apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  strategy:
    rollingUpdate:
      maxSurge: 35%
      maxUnavailable: 35%
  replicas: 10
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
        - name: app
          image: gdsz.harbor.com/experimental_images/hserver:v2
          readinessProbe:
            exec:
              command:
               - cat
               - /tmp/healthy
            initialDelaySeconds: 10       
            periodSeconds: 5
