apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    metadata:
      name: myjob
    spec:
      containers:
        - name: myjob
          image: gdsz.harbor.com/library/busybox:1.28.4
          command: ["echo_cmd","hello k8s job!"]
      restartPolicy: OnFailure

