apiVersion: v1
kind: Pod
metadata:
  name: busybox-test
  namespace: test
spec:
  containers:
    - name: busybox-test
      image: gdsz.harbor.com/library/busybox:1.28.4
      command: ["/bin/sh","-c","sleep 864000"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
