apiVersion: v1
kind: Pod
metadata:
   name: healthcheck
   labels:
     test: healthcheck
spec:
  restartPolicy: OnFailure
  containers:
    - name: healthcheck
      image: gdsz.harbor.com/library/busybox:latest
      args:
         - /bin/sh
         - -c
         - sleep 10; exit 1  
