apiVersion: v1
kind: Pod
metadata:
  name: configmap-env
spec:
  containers:
    - name: configmap-env
      image: gdsz.harbor.com/library/busybox:1.28.4
      args:
        - /bin/sh
        - -c
        - sleep 30000
      env:
        - name: CONFIG_1
          valueFrom:
            configMapKeyRef: 
              name: myconfigmap
              key: config1
        - name: CONFIG_2
          valueFrom:
            configMapKeyRef: 
              name: myconfigmap
              key: config2
