apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob
              image: gdsz.harbor.com/library/busybox:1.28.4
              command: ["echo","hello k8s job -- cron->Job"]
          restartPolicy: OnFailure    
