apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job
  namespace: test
  labels:
    app: cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: cron-job
    spec:
      parallelism: 2
      template:
        spec:
          containers:
            - name: cron-job
              image: gdsz.harbor.com/library/busybox:1.28.4
              command:
              - /bin/sh
              - -c
              - date; echo hello from the kubernetes cluster; sleep 10
          restartPolicy: OnFailure        
