apiVersion: v1
kind: Pod
metadata:
  name: producer-consumer
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
  containers:
    - name: producer
      image: gdsz.harbor.com/library/busybox:1.28.4
      volumeMounts:
        - mountPath: /producer_dir
          name: shared-volume
      args:
        - /bin/sh
        - -c 
        - echo "hello word" > /producer_dir/hello; sleep 30000
    - name: consumer
      image: gdsz.harbor.com/library/busybox:1.28.4
      volumeMounts:
        - mountPath: /consumer_dir
          name: shared-volume
      args:
        - /bin/sh
        - -c
        - cat /consuemr_dir/hello; sleep 300000

