apiVersion: apps/v1
kind: Deployment
metadata:
   name: httpd
spec:
  selector:
    matchLabels:
      run: httpd
  replicas: 3
  template:
    metadata:
      labels:
        run: httpd
    spec:
      containers:
       - name: httpd
         image: gdsz.harbor.com/experimental_images/httpd:latest
         ports:
           - containerPort: 80
