apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-test
  template:
    metadata:
      labels:
        app: httpd-test
    spec:
      containers:
        - name: httpd-test
          image: gdsz.harbor.com/experimental_images/httpd:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: http-test-svc
spec:
  selector:
    app: httpd-test
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000
