apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: test
spec:
  revisionHistoryLimit: 10
  replicas: 4
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: gdsz.harbor.com/experimental_images/nginx:v1 
          ports:
            - containerPort: 80
