apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-dev
  namespace: kube-public
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-dev
  template:
    metadata:
      labels:
        app: httpd-dev
    spec:
      containers:
        - name: httpd-dev
          image: gdsz.harbor.com/experimental_images/httpd:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-dev-svc
  namespace: kube-public
spec:
  selector:
    app: httpd-dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
