apiVersion: v1
kind: Pod
metadata:
  name: init-container
  namespace: test
spec:
  containers:
    - name: main-busybox
      image: gdsz.harbor.com/library/busybox:1.28.4
      command: ["/bin/sh","-c","sleep 30000"]
  initContainers:
    - name: init-container
      image: gdsz.harbor.com/library/busybox:1.28.4
      command: ["/bin/sh","-c","sleep 30"]
