apiVersion: batch/v1
kind: Job
metadata:
  name: job-one
  namespace: test
spec:
  template:
    spec:
      containers:
        - name: job-one
          image: gdsz.harbor.com/library/busybox:1.28.4
          command: ["/bin/sh","-c","sleep 120"]
      restartPolicy: Never   
