apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
  namespace: test
  labels:
    test: liveness-exec
spec:
  containers:
    - name: liveness-exec-demo
      image: gdsz.harbor.com/library/busybox:1.28.4
      args: ["/bin/sh","-c"," touch /tmp/healthy; sleep 60; rm -rf /tmp/healthy; sleep 1200"]
      livenessProbe:
        exec:
          command: ["test","-e","/tmp/healthy"]
        initialDelaySeconds: 10  
        periodSeconds: 5

