apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path:  /data/volumes/v2/mysql-pvc
    server: 192.168.0.80
