apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-v1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/volumes/v1/mysql-data
    server: 192.168.0.80


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-v1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs    
