apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dev-deployment
spec:
  selector:
    matchLabels:
      app: nginx-web
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
        - name: nginx-web
          image: gdsz.harbor.com/experimental_images/nginx:v1
