apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test
spec:
  #sessionAffinity: ClientIP
  #sessionAffinityConfig:
  #  clientIP:
  #    timeoutSeconds: 60
  type: NodePort
  #type: LoadBalancer
  #selector:
  #  app: nginx-app
  #ports:
  #  - protocol: TCP
  #    port: 80
  #    targetPort: 80
  #    nodePort: 32223
  #type: ExternalName
  #externalName: nginx.k8s.io
  #clusterIP: None
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      #name: httpport
      

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: gdsz.harbor.com/experimental_images/nginx:v1
          ports:
            - containerPort: 80

