apiVersion: v1
kind: Pod
metadata:
  name: pod-env
spec:
  containers:
    - name: pod-env
      image: gdsz.harbor.com/library/busybox:1.28.4
      args:
        - /bin/sh
        - -c
        - sleep 30000
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
