apiVersion: v1
kind: Secret
metadata:
  name: mysqlinfo
data:
  username: cm9vdA==
  password: YWJjLTA5MTIyMA==

---
apiVersion: v1
kind: Pod
metadata:
  name: info-sec
spec:
  containers:
    - image: gdsz.harbor.com/library/busybox:1.28.4
      name: info-sec
      args:
        - /bin/sh
        - -c 
        - sleep 30000
      volumeMounts:
        - name: info-sec
          mountPath: /etc/info
          readOnly: true
  volumes:
    - name: info-sec
      secret:
        secretName: mysqlinfo
