apiVersion: v1
kind: Pod
metadata:
  name: pod-with-labels
  namespace: test
  labels:
    env: qa
    tier: frontend
spec:
  containers:
    - name: podlabels
      image: gdsz.harbor.com/library/busybox:1.28.4
      command: ["/bin/sh","-c","sleep 30000"]
