apiVersion: v1
kind: Pod
metadata:
  name: post-start
  namespace: test
spec:
  containers:
    - name: post-start
      image: gdsz.harbor.com/library/busybox:1.28.4
      command: ["/bin/sh","-c","sleep 30000"]
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh","-c","echo 'lifecycle hook handler' >/tmp/hook.db"]
