apiVersion: v1
kind: Service
metadata:
  name: readiness-svc
spec:
  selector:
    test: readiness
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 8080
      targetPort: 80
      
