apiVersion: v1
kind: Service
metadata:
  name: re-http-svc
  namespace: test
spec:
  selector:
    test: readiness-http
  ports:
    - targetPort: 80
      port: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: readiness-http
  labels:
    test: readiness-http
  namespace: test
spec:
  containers:
    - name: readiness-http
      image: gdsz.harbor.com/experimental_images/nginx:v1
      ports:
        - name: http
          containerPort: 80
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh","-c","echo halthy > /usr/local/nginx/html/healthz"]
      readinessProbe:
        httpGet:
          path: /healthz
          port: http
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 3
