apiVersion: v1
kind: Pod
metadata:
  name: test-cmd
  namespace: test
spec:
  containers:
    - name: test-cmd
      image: gdsz.harbor.com/library/busybox:1.28.4
      command: ["/bin/sh"]
      args: ["-c","while true; do echo 'sleep 30'; sleep 30;done"]
      env:
        - name: REDIS_HOST
          value: 192.168.0.103:6379
        - name: LOG_LEVEL
          value: info
